name: "myaction"
description: "my action"

inputs:

runs:
  using: composite
  steps:
    - sehll: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        python3 -m myaction \
          --github-repository="${{ inputs.repository }}" \
          --github-token="${{ inputs.token }}" 
